"""add country and original_language and remove watch_status from Media

Revision ID: 177aaa3bf194
Revises: f98e2ea1f6e6
Create Date: 2026-07-23 23:06:59.352912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '177aaa3bf194'
down_revision: Union[str, Sequence[str], None] = 'f98e2ea1f6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('media', sa.Column('original_language', sa.String(length=255), nullable=True))
    op.drop_column('media', 'watch_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('watch_status', postgresql.ENUM('plan_to_watch', 'watching', 'completed', 'on_hold', 'dropped', 'loved', name='watchstatus'), autoincrement=False, nullable=True))
    op.drop_column('media', 'original_language')
    op.drop_column('media', 'country')
    # ### end Alembic commands ###
