"""update season and episode models

Revision ID: 2cd07f22b31a
Revises: 58824874dac8
Create Date: 2026-07-24 01:33:28.372060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd07f22b31a'
down_revision: Union[str, Sequence[str], None] = '58824874dac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('release_date', sa.Date(), nullable=True))
    op.drop_column('episodes', 'air_date')
    op.add_column('seasons', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('seasons', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('seasons', sa.Column('tmdb_rating', sa.Float(), nullable=True))
    op.drop_column('seasons', 'air_year')
    op.drop_column('seasons', 'name')
    op.drop_column('seasons', 'poster_url')
    op.drop_column('seasons', 'episode_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('episode_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('seasons', sa.Column('poster_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('seasons', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('seasons', sa.Column('air_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('seasons', 'tmdb_rating')
    op.drop_column('seasons', 'release_date')
    op.drop_column('seasons', 'title')
    op.add_column('episodes', sa.Column('air_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('episodes', 'release_date')
    # ### end Alembic commands ###
