"""add community_ratings_count to medi model

Revision ID: 3beb5a333b0b
Revises: 3ee3c7b80f59
Create Date: 2026-07-25 19:57:09.441464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3beb5a333b0b'
down_revision: Union[str, Sequence[str], None] = '3ee3c7b80f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('community_ratings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'community_ratings_count')
    # ### end Alembic commands ###
