"""allow same tmdb_id for movie and series

Revision ID: 3ee3c7b80f59
Revises: d6ec84d47e2b
Create Date: 2026-07-25 19:21:20.063376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee3c7b80f59'
down_revision: Union[str, Sequence[str], None] = 'd6ec84d47e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_tmdb_id'), table_name='media')
    op.create_index(op.f('ix_media_tmdb_id'), 'media', ['tmdb_id'], unique=False)
    op.create_unique_constraint('uq_media_tmdb_type', 'media', ['tmdb_id', 'media_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_media_tmdb_type', 'media', type_='unique')
    op.drop_index(op.f('ix_media_tmdb_id'), table_name='media')
    op.create_index(op.f('ix_media_tmdb_id'), 'media', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###
