"""add seasons and episodes tables

Revision ID: 58824874dac8
Revises: f3e59da5fd1e
Create Date: 2026-07-24 01:22:46.290813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58824874dac8'
down_revision: Union[str, Sequence[str], None] = 'f3e59da5fd1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('air_year', sa.Integer(), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'season_number')
    )
    op.create_table('episodes',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('tmdb_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['media_id', 'season_number'], ['seasons.media_id', 'seasons.season_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'season_number', 'episode_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    op.drop_table('seasons')
    # ### end Alembic commands ###
