"""Add CHECK constraint for rating 1-5

Revision ID: d6ec84d47e2b
Revises: 815f651a20c3
Create Date: 2026-07-25 17:02:53.230821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ec84d47e2b'
down_revision: Union[str, Sequence[str], None] = '815f651a20c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE user_ratings ADD CONSTRAINT chk_rating_range CHECK (rating >= 1 AND rating <= 5)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE user_ratings DROP CONSTRAINT IF EXISTS chk_rating_range")
    # ### end Alembic commands ###
