"""update refresh token to token_hash

Revision ID: f1bd5471e20a
Revises: 6f7083d5d8d3
Create Date: 2026-07-22 19:51:49.976080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1bd5471e20a'
down_revision: Union[str, Sequence[str], None] = '6f7083d5d8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('personal_list_items', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_personal_list_item', 'personal_list_items', ['list_id', 'media_id'])
    op.alter_column('personal_lists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_personal_list_user_name', 'personal_lists', ['user_id', 'name'])
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(length=64), nullable=False))
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', type_='unique')
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    op.drop_column('refresh_tokens', 'token')
    op.alter_column('reviews', 'contains_spoiler',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_review_user_media', 'reviews', ['user_id', 'media_id'])
    op.alter_column('user_ratings', 'rated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_rating_user_media', 'user_ratings', ['user_id', 'media_id'])
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('watch_progress', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('watch_progress', 'watched_episodes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watch_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_watch_progress_user_media', 'watch_progress', ['user_id', 'media_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_watch_progress_user_media', 'watch_progress', type_='unique')
    op.alter_column('watch_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('watch_progress', 'watched_episodes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('watch_progress', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('uq_rating_user_media', 'user_ratings', type_='unique')
    op.alter_column('user_ratings', 'rated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_review_user_media', 'reviews', type_='unique')
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'contains_spoiler',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.create_unique_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('refresh_tokens', 'token_hash')
    op.drop_constraint('uq_personal_list_user_name', 'personal_lists', type_='unique')
    op.alter_column('personal_lists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_personal_list_item', 'personal_list_items', type_='unique')
    op.alter_column('personal_list_items', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
