"""add community rating genres and cast to media

Revision ID: f3e59da5fd1e
Revises: 177aaa3bf194
Create Date: 2026-07-23 23:11:14.283366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3e59da5fd1e'
down_revision: Union[str, Sequence[str], None] = '177aaa3bf194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('community_rating', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('media', sa.Column('cast', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'cast')
    op.drop_column('media', 'genres')
    op.drop_column('media', 'community_rating')
    # ### end Alembic commands ###
